import type { Card, CardCollection } from './models';

export const baseCollections: Record<string, CardCollection> = {
  celebrations: {
    colors: { bg: '#FFF5EB', fg: '#C4724E', mutedBg: '#FFF9F5', mutedFg: '#E8A87C' },
    cards: [
      {
        id: 'australia-birthday',
        name: 'Outback Birthday',
        occasion: 'Birthday',
        style: 'illustrated',
        tone: 'warm',
        colors: ['Terracotta', 'Cream'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Cotton 110lb',
        description: 'Vintage Australian stamp design celebrating another year around the sun.',
        src: '/cards/australia.jpeg',
        srcLg: '/cards/australia.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 0.85,
      },
      {
        id: 'ghana-celebration',
        name: 'Golden Celebration',
        occasion: 'Birthday',
        style: 'illustrated',
        tone: 'playful',
        colors: ['Gold', 'Green'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Matte 100lb',
        description: 'Vibrant Ghanaian stamp art celebrating life\'s joyful moments.',
        src: '/cards/ghana.jpeg',
        srcLg: '/cards/ghana.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 1.1,
      },
      {
        id: 'vatican-milestone',
        name: 'Milestone Achievement',
        occasion: 'Congratulations',
        style: 'illustrated',
        tone: 'elegant',
        colors: ['Burgundy', 'Gold'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Premium Smooth 120lb',
        description: 'Ornate Vatican stamp design for major life achievements.',
        src: '/cards/vatican.jpeg',
        srcLg: '/cards/vatican.jpeg',
        pricing: { physical: 14.99, digital: 5.99, currency: 'USD' },
        inStock: true,
        aspect: 0.7,
      },
      {
        id: 'monaco-victory',
        name: 'Monaco Victory',
        occasion: 'Congratulations',
        style: 'illustrated',
        tone: 'elegant',
        colors: ['Red', 'White'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Linen 110lb',
        description: 'Classic Monaco stamp art celebrating victories and achievements.',
        src: '/cards/monaco.jpeg',
        srcLg: '/cards/monaco.jpeg',
        pricing: { physical: 12.99, digital: 4.99, currency: 'USD' },
        inStock: true,
        aspect: 1.3,
      },
      {
        id: 'usa-mississippi',
        name: 'River Birthday',
        occasion: 'Birthday',
        style: 'illustrated',
        tone: 'warm',
        colors: ['Blue', 'Brown'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Cotton 100lb',
        description: 'Vintage American stamp featuring the mighty Mississippi.',
        src: '/cards/USA-mississippi.jpeg',
        srcLg: '/cards/USA-mississippi.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 0.9,
      },
    ],
  },
  gratitude: {
    colors: { bg: '#FAFAF8', fg: '#2C2C2C', mutedBg: '#FFFFFF', mutedFg: '#666666' },
    cards: [
      {
        id: 'great-britain-thanks',
        name: 'Royal Thanks',
        occasion: 'Thank You',
        style: 'illustrated',
        tone: 'elegant',
        colors: ['Navy', 'Crimson'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Linen 100lb',
        description: 'Classic British stamp design for elegant expressions of gratitude.',
        src: '/cards/great-britain.jpeg',
        srcLg: '/cards/great-britain.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 0.75,
      },
      {
        id: 'canada-gratitude',
        name: 'Northern Thanks',
        occasion: 'Thank You',
        style: 'illustrated',
        tone: 'warm',
        colors: ['Red', 'White'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Cotton 100lb',
        description: 'Vintage Canadian stamp art expressing heartfelt appreciation.',
        src: '/cards/canada.jpeg',
        srcLg: '/cards/canada.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 1.2,
      },
      {
        id: 'latvia-appreciation',
        name: 'Baltic Appreciation',
        occasion: 'Thank You',
        style: 'illustrated',
        tone: 'serene',
        colors: ['Maroon', 'Gold'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Premium Smooth 110lb',
        description: 'Latvian stamp beauty for meaningful thank you moments.',
        src: '/cards/latvia.jpeg',
        srcLg: '/cards/latvia.jpeg',
        pricing: { physical: 10.99, digital: 3.49, currency: 'USD' },
        inStock: true,
        aspect: 0.65,
      },
      {
        id: 'sweden-thanks',
        name: 'Nordic Gratitude',
        occasion: 'Thank You',
        style: 'illustrated',
        tone: 'minimal',
        colors: ['Blue', 'Yellow'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Recycled 100lb',
        description: 'Clean Swedish stamp design for modern expressions of thanks.',
        src: '/cards/sweden.jpeg',
        srcLg: '/cards/sweden.jpeg',
        pricing: { physical: 12.99, digital: 4.49, currency: 'USD' },
        inStock: true,
        aspect: 1.0,
      },
    ],
  },
  seasonal: {
    colors: { bg: '#1B4332', fg: '#D4AF37', mutedBg: '#2D5A45', mutedFg: '#B8963A' },
    cards: [
      {
        id: 'usa-christmas',
        name: 'American Christmas',
        occasion: 'Holiday',
        style: 'illustrated',
        tone: 'festive',
        colors: ['Red', 'Green'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Velvet 110lb',
        description: 'Classic American Christmas stamp for warm holiday wishes.',
        src: '/cards/USA-christmas.jpeg',
        srcLg: '/cards/USA-christmas.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 0.8,
      },
      {
        id: 'ceskoslovensko-winter',
        name: 'Czech Winter',
        occasion: 'Holiday',
        style: 'illustrated',
        tone: 'serene',
        colors: ['Ice Blue', 'Silver'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Pearl 100lb',
        description: 'Czechoslovakian stamp art capturing winter\'s quiet beauty.',
        src: '/cards/ceskoslovensko.jpeg',
        srcLg: '/cards/ceskoslovensko.jpeg',
        pricing: { physical: 12.99, digital: 4.49, currency: 'USD' },
        inStock: true,
        aspect: 1.15,
      },
      {
        id: 'nicaragua-spring',
        name: 'Tropical Spring',
        occasion: 'Spring',
        style: 'illustrated',
        tone: 'playful',
        colors: ['Lavender', 'Yellow'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Matte 100lb',
        description: 'Nicaraguan stamp celebrating vibrant spring colors.',
        src: '/cards/nicaragua.jpeg',
        srcLg: '/cards/nicaragua.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 0.7,
      },
      {
        id: 'jugoslavija-autumn',
        name: 'Balkan Autumn',
        occasion: 'Fall',
        style: 'illustrated',
        tone: 'warm',
        colors: ['Burnt Orange', 'Brown'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Kraft 100lb',
        description: 'Yugoslavian stamp with warm autumn harvest tones.',
        src: '/cards/jugoslavija.jpeg',
        srcLg: '/cards/jugoslavija.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 1.4,
      },
      {
        id: 'czechoslovakia-newyear',
        name: 'New Year\'s Eve',
        occasion: 'New Year',
        style: 'illustrated',
        tone: 'elegant',
        colors: ['Black', 'Gold'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Black Velvet 110lb',
        description: 'Elegant Czech stamp design for ringing in the new year.',
        src: '/cards/czechoslovakia.jpeg',
        srcLg: '/cards/czechoslovakia.jpeg',
        pricing: { physical: 14.99, digital: 5.99, currency: 'USD' },
        inStock: true,
        aspect: 0.9,
      },
    ],
  },
  everyday: {
    colors: { bg: '#E8F4F8', fg: '#5B8A9A', mutedBg: '#F2F9FB', mutedFg: '#8BB5C4' },
    cards: [
      {
        id: 'usa-voting',
        name: 'Civic Hello',
        occasion: 'Just Because',
        style: 'illustrated',
        tone: 'warm',
        colors: ['Red', 'Blue'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Cotton 100lb',
        description: 'Vintage American democracy stamp for everyday correspondence.',
        src: '/cards/USA-voting.jpeg',
        srcLg: '/cards/USA-voting.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 1.1,
      },
      {
        id: 'monaco-thinking',
        name: 'Mediterranean Thoughts',
        occasion: 'Just Because',
        style: 'illustrated',
        tone: 'serene',
        colors: ['Azure', 'White'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Matte 100lb',
        description: 'Monaco stamp art for when someone\'s on your mind.',
        src: '/cards/monaco.jpeg',
        srcLg: '/cards/monaco.jpeg',
        pricing: { physical: 10.99, digital: 3.49, currency: 'USD' },
        inStock: true,
        aspect: 0.75,
      },
      {
        id: 'australia-courage',
        name: 'Outback Courage',
        occasion: 'Encouragement',
        style: 'illustrated',
        tone: 'warm',
        colors: ['Mustard', 'Terracotta'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Cotton 100lb',
        description: 'Australian stamp strength for words of encouragement.',
        src: '/cards/australia.jpeg',
        srcLg: '/cards/australia.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 0.85,
      },
      {
        id: 'ghana-missing',
        name: 'Golden Distance',
        occasion: 'Just Because',
        style: 'illustrated',
        tone: 'warm',
        colors: ['Gold', 'Green'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Linen 100lb',
        description: 'Ghanaian stamp warmth for when you miss someone.',
        src: '/cards/ghana.jpeg',
        srcLg: '/cards/ghana.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 1.25,
      },
      {
        id: 'vatican-everyday',
        name: 'Sacred Hello',
        occasion: 'Just Because',
        style: 'illustrated',
        tone: 'elegant',
        colors: ['Burgundy', 'Ivory'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Premium Smooth 120lb',
        description: 'Vatican stamp elegance for meaningful everyday moments.',
        src: '/cards/vatican.jpeg',
        srcLg: '/cards/vatican.jpeg',
        pricing: { physical: 9.99, digital: 2.99, currency: 'USD' },
        inStock: true,
        aspect: 0.95,
      },
      {
        id: 'great-britain-hello',
        name: 'British Greetings',
        occasion: 'Just Because',
        style: 'illustrated',
        tone: 'elegant',
        colors: ['Navy', 'Red'],
        size: 'A2 (4.25 x 5.5)',
        paperStock: 'Linen 110lb',
        description: 'Classic British stamp for proper everyday correspondence.',
        src: '/cards/great-britain.jpeg',
        srcLg: '/cards/great-britain.jpeg',
        pricing: { physical: 11.99, digital: 3.99, currency: 'USD' },
        inStock: true,
        aspect: 0.8,
      },
    ],
  },
};

export const collections = Object.fromEntries(
  Object.entries(baseCollections).map(([key, value]) => [
    key,
    {
      ...value,
      cards: value.cards.map((card, index) => ({
        ...card,
        id: card.id || `${key}-${index}`,
      })),
    },
  ]),
);

export type CollectionType = keyof typeof baseCollections;

export const collectionTypes = Object.keys(collections) as CollectionType[];

export const collectionFilters = ['all', 'celebrations', 'gratitude', 'seasonal', 'everyday'] as const;

export type CollectionFilter = (typeof collectionFilters)[number];

export const cards = Object.entries(collections).flatMap(([collectionKey, collection]) =>
  collection.cards.map((card) => ({
    ...card,
    collection: collectionKey as Exclude<CollectionFilter, 'all'>,
  })),
);
